- migrations/1654545715004_rentals.ts
This PR adds the rentals, metadata and periods tables.
Closes #10
> feat: Rentals, metadata and periods tables

- src/ports/schema-validator/schema-validator-middleware.ts
- src/ports/schema-validator/schema-validator.ts
This PR improves the schema validation port performance by compiling the schemas once to later re-use them.
> fix: Improve schema validation performance

- src/components.ts
- src/ports/job/component.ts
- src/ports/job/index.ts
- src/ports/job/types.ts
- src/types.ts
- test/components.ts
- test/unit/job-component.spec.ts
- test/unit/schema-validator.spec.ts
This PR adds a job component to later be used to handle the refresh job.
> feat: Job component

- src/ports/rentals/component.ts
- src/ports/rentals/types.ts
- test/unit/rentals-component.spec.ts
This PR changes the ownership check to verify if the NFT is owned by the lessor through the rental contract.
> fix: Ownership check

- .github/workflows/node.yml
- README.md
This PR adds coveralls coverage report to the repository.
> feat: Add coveralls coverage report

- src/controllers/handlers/rentals-handlers.ts
- src/controllers/routes.ts
- test/unit/rentals-handler.spec.ts
This PR adds the `/v1/` initial string to the new endpoints.
> fix: Add version to endpoints

- src/controllers/handlers/rentals-handlers.ts
- src/logic/rentals/ethereum.ts
- test/unit/rentals-handler.spec.ts
- test/unit/rentals-logic.spec.ts
This PR fixes the rentals signature failing due to nonces being defined as an array with length 3.
> fix: Rental nonces in signature

- package-lock.json
- package.json
- test/unit/http-logic.spec.ts
- test/unit/rentals-component.spec.ts
This PR updates the category filter to fix the requests done with the category as parcel.
> fix: Category filter

- src/ports/rentals/component.ts
- src/ports/rentals/types.ts
- test/unit/rentals-component.spec.ts
> feat: mark the rental as cancelled if a nonce was bumped

- src/ports/rentals/component.ts
- src/ports/rentals/types.ts
- test/unit/rentals-component.spec.ts
Based on [#https://github.com/decentraland/rentals-graph/pull/14](https://github.com/decentraland/rentals-graph/pull/14) changes
> feat: Update to the latest contract changes

- src/components.ts
- src/migrations/1654545715004_rentals.ts
- src/ports/rentals/component.ts
- src/ports/rentals/types.ts
- src/types.ts
- test/components.ts
- test/unit/rentals-component.spec.ts
- test/unit/schema-validator.spec.ts
> feat: Add a job to cancel rentals that had a nonce bump

- package-lock.json
- package.json
> chore: update the transactions lib

- package-lock.json
- package.json
- src/adapters/rentals/rentals.ts
- src/logic/rentals/ethereum.ts
- src/logic/rentals/types.ts
- src/migrations/1654545715004_rentals.ts
- src/migrations/1666280846241_add-indexes-to-update-type.ts
- src/migrations/1666283185308_add-target-column-to-rentals.ts
- src/ports/rentals/component.ts
- src/ports/rentals/types.ts
- test/unit/rentals-adapters.spec.ts
- test/unit/rentals-component.spec.ts
- test/unit/rentals-handler.spec.ts
- test/unit/rentals-logic.spec.ts
> feat: Add "target" to signature check and db

- src/ports/rentals/component.ts
- src/ports/rentals/types.ts
- test/unit/rentals-component.spec.ts
> feat: Cancel listings if the asset bump was of type CANCEL

- src/ports/rentals/component.ts
> fix: return the "periods" object as the other endpoints

- src/migrations/1667818838202_add-rentedDays-and-periodChosen-columns.ts
- src/ports/rentals/component.ts
> feat: Add "rentedDay" and "periodChosen" columns

- package-lock.json
- package.json
- src/adapters/rentals/rentals.ts
- src/ports/rentals/types.ts
- test/unit/rentals-adapters.spec.ts
- test/unit/rentals-handler.spec.ts
> feat: Add "rentedDays" to the rental listing response

- src/ports/rentals/component.ts
> fix: Move to CLAIMED just the old rentals

- src/ports/rentals/component.ts
> fix: Retrieve ends at from the graph

- package-lock.json
- package.json
This PR updates the decentraland transactions package which contains the new address for the rentals contract in production.
> fix: Update decentraland transactions

- package-lock.json
- package.json
This PR updates the graph component to receive the configuration parameter to set the agent name.
> fix: Upgrade graph component

- src/controllers/handlers/rentals-handlers.ts
- src/ports/rentals/component.ts
- src/ports/rentals/errors.ts
- test/unit/rentals-component.spec.ts
- test/unit/rentals-handler.spec.ts
This PR prevents the creation of expired rental listings.
Closes #191
> fix: Prevent the creation of expired rental listings

- src/controllers/handlers/rentals-handlers.ts
- src/ports/rentals/component.ts
- src/ports/rentals/errors.ts
- src/ports/rentals/types.ts
- test/unit/rentals-component.spec.ts
- test/unit/rentals-handler.spec.ts
> fix: Prevent dissolved estates from being listed

- test/unit/rentals-component.spec.ts
reuse startDate and not create a new date as it is causing the test to be flaky
> fix: test date not being reused

- .env.default
- .github/workflows/node.yml
- Dockerfile
- src/components.ts
This PR makes it possible to use regexes as the CORS origins.
> feat: Allow CORS origins to use regex
